# Generated by Django 5.0.4 on 2024-05-25 20:08

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0015_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id_state', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Typestates',
            fields=[
                ('id_type_state', models.AutoField(primary_key=True, serialize=False)),
                ('type_state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bedrooms',
            fields=[
                ('id_bedroom', models.AutoField(primary_key=True, serialize=False)),
                ('bedroom_name', models.CharField(max_length=40)),
                ('people_limit', models.IntegerField()),
                ('people_amount', models.IntegerField(default=0)),
                ('photo', models.ImageField(null=True, upload_to='imagenes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_state', models.ForeignKey(db_column='id_state', default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='appVillaJair.states')),
            ],
        ),
        migrations.AddField(
            model_name='states',
            name='id_type_state',
            field=models.ForeignKey(db_column='id_type_state', on_delete=django.db.models.deletion.DO_NOTHING, to='appVillaJair.typestates'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField()),
                ('nit', models.BigIntegerField()),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.BigIntegerField()),
                ('country', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('id_state', models.ForeignKey(blank=True, db_column='id_state', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appVillaJair.states')),
            ],
        ),
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id_register', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_bedroom', models.ForeignKey(db_column='id_bedroom', on_delete=django.db.models.deletion.DO_NOTHING, to='appVillaJair.bedrooms')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='registers', to='appVillaJair.users')),
            ],
        ),
    ]
