# Generated by Django 5.0.4 on 2024-05-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
