# Generated by Django 4.1.3 on 2024-05-01 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
