# Generated by Django 4.1.3 on 2024-05-01 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appVillaJair', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedrooms',
            fields=[
                ('id_bedroom', models.AutoField(primary_key=True, serialize=False)),
                ('bedroom_name', models.CharField(max_length=40)),
                ('people_limit', models.IntegerField(max_length=2)),
                ('people_amount', models.IntegerField(max_length=2)),
                ('photo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id_state', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Typestates',
            fields=[
                ('id_type_state', models.AutoField(primary_key=True, serialize=False)),
                ('type_state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone_number', models.BigIntegerField()),
                ('country', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('id_bedroom', models.ForeignKey(blank=True, db_column='id_bedroom', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appVillaJair.bedrooms')),
                ('id_role', models.ForeignKey(db_column='id_role', on_delete=django.db.models.deletion.DO_NOTHING, to='appVillaJair.role')),
                ('id_state', models.ForeignKey(blank=True, db_column='id_state', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appVillaJair.states')),
            ],
        ),
        migrations.AddField(
            model_name='states',
            name='id_type_state',
            field=models.ForeignKey(db_column='id_type_state', on_delete=django.db.models.deletion.DO_NOTHING, to='appVillaJair.typestates'),
        ),
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id_register', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('id_bedroom', models.ForeignKey(db_column='id_bedroom', on_delete=django.db.models.deletion.DO_NOTHING, to='appVillaJair.bedrooms')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='appVillaJair.users')),
            ],
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id_credential', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVillaJair.users')),
            ],
        ),
        migrations.AddField(
            model_name='bedrooms',
            name='id_state',
            field=models.ForeignKey(db_column='id_state', on_delete=django.db.models.deletion.DO_NOTHING, to='appVillaJair.states'),
        ),
    ]
