# Generated by Django 5.0.4 on 2024-05-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0002_remove_registers_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-26 20:52:00-05'),
            preserve_default=False,
        ),
    ]
