# Generated by Django 4.1.3 on 2024-05-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials',
            old_name='id_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='bedrooms',
            name='people_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bedrooms',
            name='people_limit',
            field=models.IntegerField(),
        ),
    ]
