# Generated by Django 5.0.4 on 2024-05-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0003_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrooms',
            name='people_amount',
            field=models.IntegerField(),
        ),
    ]
