# Generated by Django 5.0.4 on 2024-05-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0004_rename_id_user_credentials_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrooms',
            name='photo',
            field=models.TextField(default=None, null=True),
        ),
    ]
