# Generated by Django 5.0.4 on 2024-05-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0004_alter_bedrooms_people_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrooms',
            name='people_amount',
            field=models.IntegerField(null=True),
        ),
    ]
