# Generated by Django 5.0.4 on 2024-05-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0005_alter_bedrooms_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='check_in_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registers',
            name='check_out_date',
            field=models.DateTimeField(),
        ),
    ]
