# Generated by Django 5.0.4 on 2024-05-09 23:56

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0006_alter_registers_check_in_date_and_more'),
        ('auth', '0013_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='bedrooms',
            name='photo',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(unique=True),
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
