# Generated by Django 5.0.4 on 2024-05-13 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0007_customuser_alter_bedrooms_photo_alter_users_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrooms',
            name='id_state',
            field=models.ForeignKey(db_column='id_state', default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='appVillaJair.states'),
        ),
        migrations.AlterField(
            model_name='bedrooms',
            name='people_amount',
            field=models.IntegerField(default=0),
        ),
    ]
