# Generated by Django 5.0.4 on 2024-05-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0008_alter_bedrooms_id_state_alter_bedrooms_people_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedrooms',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
