# Generated by Django 5.0.4 on 2024-05-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0009_delete_customuser_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrooms',
            name='photo',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
