# Generated by Django 5.0.4 on 2024-05-20 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0009_bedrooms_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id_bedroom',
        ),
    ]
