# Generated by Django 5.0.4 on 2024-05-20 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0010_remove_users_id_bedroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id_role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
