# Generated by Django 5.0.4 on 2024-05-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0011_remove_users_id_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
