# Generated by Django 5.0.4 on 2024-05-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0012_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='document_type',
            field=models.CharField(default='CC'),
            preserve_default=False,
        ),
    ]
