# Generated by Django 5.0.4 on 2024-05-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0013_users_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nit',
            field=models.BigIntegerField(),
        ),
    ]
