# Generated by Django 5.0.4 on 2024-05-29 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVillaJair', '0014_alter_users_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='registers', to='appVillaJair.users'),
        ),
    ]
